import Head from 'next/head';
import Link from 'next/link';
import { GiFilmProjector } from 'react-icons/gi';
import { RiHomeFill, RiUserHeartLine } from 'react-icons/ri';
import { BiCompass } from 'react-icons/bi';
import { FiUser } from 'react-icons/fi';
import { CgMediaLive } from 'react-icons/cg';
import { IoMdStopwatch, IoMdExit } from 'react-icons/io';
import { HiOutlineCog } from 'react-icons/hi';
import { Container, Wrapper } from './Styles';
import {
	NavBar,
	LogoContainer,
	LogoText,
	LogoTextPeriod,
	FlexRow,
	MenuItemContainer,
	MenuHeading,
	MenuText
} from './NavBar.js';

const menuItems = [
	{
		icon: RiHomeFill,
		text: 'Home',
		selected: true
	},
	{
		icon: BiCompass,
		text: 'Discovery'
	},
	{
		icon: IoMdStopwatch,
		text: 'Coming Soon'
	}
];

const socialMenuItems = [
	{
		icon: FiUser,
		text: 'Friends'
	},
	{
		icon: RiUserHeartLine,
		text: 'Parties'
	},
	{
		icon: CgMediaLive,
		text: 'Media'
	}
];

const generalMenuItems = [
	{
		icon: HiOutlineCog,
		text: 'Settings'
	},
	{
		icon: IoMdExit,
		text: 'Log Out'
	}
];

const Layout = (props) => {
	let iconColor = '#D22F27';
	let menuItemColor = '#6B6C74';
	let menuItemHeading = '#9597A1';
	return (
		<Wrapper>
			<Container>
				<Head>
					<title>TrailorBox</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.ico' />
				</Head>
				<NavBar>
					<Link href='/' passHref>
						<LogoContainer>
							<GiFilmProjector style={{ color: iconColor }} size={40} />

							<LogoText>
								TrailerBox<LogoTextPeriod>.</LogoTextPeriod>
							</LogoText>
						</LogoContainer>
					</Link>

					<MenuHeading style={{ marginBottom: 20, color: menuItemHeading }}>
						Menu
					</MenuHeading>
					<MenuItemContainer>
						{menuItems.map((menuItem, index) => (
							<>
								<FlexRow
									key={index}
									style={{
										borderRight: menuItem.selected ? 'solid 5px #D22F27' : null
									}}
								>
									<menuItem.icon
										style={{
											color: menuItem.selected ? '#D22F27' : menuItemColor
										}}
										size={30}
									/>

									<MenuText
										style={{
											color: menuItem.selected ? '#fff' : menuItemColor,
											width: '100%'
										}}
									>
										{menuItem.text}
									</MenuText>
								</FlexRow>
							</>
						))}
					</MenuItemContainer>
					<MenuHeading
						style={{ marginTop: 35, marginBottom: 20, color: menuItemHeading }}
					>
						Social
					</MenuHeading>
					<MenuItemContainer>
						{socialMenuItems.map((menuItem, index) => (
							<>
								<FlexRow key={index}>
									<menuItem.icon
										style={{
											color: menuItem.selected ? '#D22F27' : menuItemColor
										}}
										size={30}
									/>
									<MenuText
										style={{
											color: menuItem.selected ? '#fff' : menuItemColor,
											width: '100%',
											borderRight: menuItem.selected
												? 'solid 5px #D22F27'
												: null
										}}
									>
										{menuItem.text}
									</MenuText>
								</FlexRow>
							</>
						))}
					</MenuItemContainer>
					<MenuHeading
						style={{ marginTop: 35, marginBottom: 20, color: menuItemHeading }}
					>
						General
					</MenuHeading>
					<MenuItemContainer>
						{generalMenuItems.map((menuItem, index) => (
							<>
								<FlexRow key={index}>
									<menuItem.icon
										style={{
											color: menuItem.selected ? '#D22F27' : menuItemColor
										}}
										size={30}
									/>
									<MenuText
										style={{
											color: menuItem.selected ? '#fff' : menuItemColor,
											width: '100%',
											borderRight: menuItem.selected
												? 'solid 5px #D22F27'
												: null
										}}
									>
										{menuItem.text}
									</MenuText>
								</FlexRow>
							</>
						))}
					</MenuItemContainer>
				</NavBar>
				{props.children}
			</Container>
		</Wrapper>
	);
};

export default Layout;
