import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import Modal from "../Modal/Modal";
import { GiFilmProjector } from "react-icons/gi";
import { RiHomeFill, RiUserHeartLine } from "react-icons/ri";
import { BiCompass } from "react-icons/bi";
import { FiUser } from "react-icons/fi";
import { CgMediaLive } from "react-icons/cg";
import { IoMdStopwatch, IoMdExit } from "react-icons/io";
import { HiOutlineCog } from "react-icons/hi";
import { Container, Wrapper } from "./Styles";
import {
  NavBar,
  LogoContainer,
  LogoText,
  LogoTextPeriod,
  FlexRow,
  MenuItemContainer,
  MenuHeading,
  MenuText,
} from "./NavBar.js";

const menuItems = [
  {
    icon: RiHomeFill,
    text: "Home",
    selected: true,
  },
  {
    icon: BiCompass,
    text: "Discovery",
  },
  {
    icon: IoMdStopwatch,
    text: "Recommended",
  },
];

const socialMenuItems = [
  {
    icon: FiUser,
    text: "WatchList",
  },
  {
    icon: RiUserHeartLine,
    text: "Favorites",
  },
  {
    icon: CgMediaLive,
    text: "Ratings",
  },
];

const Layout = (props) => {
  let iconColor = "#D22F27";
  let menuItemColor = "#6B6C74";
  let menuItemHeading = "#9597A1";

  const [showModal, setShowModal] = useState(false);

  return (
    <Wrapper>
      <Container>
        <Head>
          <title>TrailorBox</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar>
          <Link href="/" passHref>
            <LogoContainer>
              <GiFilmProjector style={{ color: iconColor }} size={40} />

              <LogoText>
                TrailerBox<LogoTextPeriod>.</LogoTextPeriod>
              </LogoText>
            </LogoContainer>
          </Link>

          <MenuHeading style={{ marginBottom: 20 }}>Menu</MenuHeading>
          <MenuItemContainer>
            {menuItems.map((menuItem, index) => (
              <>
                <FlexRow
                  key={index}
                  //   style={{
                  //     borderRight: menuItem.selected ? "solid 5px #D22F27" : null,
                  //   }}
                >
                  <menuItem.icon
                    // style={{
                    //   color: menuItem.selected ? "#D22F27" : menuItemColor,
                    // }}
                    size={30}
                  />

                  <MenuText
                  // style={{
                  //   color: menuItem.selected ? "#fff" : menuItemColor,
                  //   width: "100%",
                  // }}
                  >
                    {menuItem.text}
                  </MenuText>
                </FlexRow>
              </>
            ))}
          </MenuItemContainer>
          <MenuHeading style={{ marginTop: 35, marginBottom: 20 }}>
            Social
          </MenuHeading>
          <MenuItemContainer>
            {socialMenuItems.map((menuItem, index) => (
              <>
                <FlexRow key={index}>
                  <menuItem.icon
                    // style={{
                    //   color: menuItem.selected ? "#D22F27" : menuItemColor,
                    // }}
                    size={30}
                  />
                  <MenuText
                  // style={{
                  //   color: menuItem.selected ? "#fff" : menuItemColor,
                  //   borderRight: menuItem.selected
                  //     ? "solid 5px #D22F27"
                  //     : null,
                  // }}
                  >
                    {menuItem.text}
                  </MenuText>
                </FlexRow>
              </>
            ))}
          </MenuItemContainer>
          <MenuHeading style={{ marginTop: 35, marginBottom: 20 }}>
            General
          </MenuHeading>
          <MenuItemContainer>
            <FlexRow>
              <HiOutlineCog size={30} />
              <MenuText>Settings</MenuText>
            </FlexRow>
            <FlexRow onClick={() => setShowModal(true)}>
              <IoMdExit size={30} />
              <MenuText>Log In</MenuText>
            </FlexRow>
          </MenuItemContainer>
        </NavBar>
        {props.children}
      </Container>
      <Modal onClose={() => setShowModal(false)} show={showModal} />
    </Wrapper>
  );
};

export default Layout;
