import Head from 'next/head';
import Link from 'next/link';
import { GiFilmProjector } from 'react-icons/gi';
import { RiHomeFill } from 'react-icons/ri';
import { BiCompass } from 'react-icons/bi';
import { IoMdStopwatch } from 'react-icons/io';
import { Container, Wrapper } from './Styles';
import {
	NavBar,
	LogoContainer,
	LogoText,
	LogoTextPeriod,
	FlexRow,
	MenuItemContainer,
	MenuHeading,
	MenuText
} from '../NavBar';

const menuItems = [
	{
		icon: RiHomeFill,
		text: 'Home',
		selected: true
	},
	{
		icon: BiCompass,
		text: 'Discovery'
	},
	{
		icon: IoMdStopwatch,
		text: 'Coming Soon'
	}
];

const Layout = (props) => {
	let iconColor = '#D22F27';
	let silver = '#6B6C74';
	let selected = true;

	return (
		<Wrapper>
			<Container>
				<Head>
					<title>TrailorBox</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.ico' />
				</Head>
				<NavBar>
					<Link href='/' passHref>
						<LogoContainer>
							<GiFilmProjector style={{ color: iconColor }} size={40} />

							<LogoText>
								TrailerBox<LogoTextPeriod>.</LogoTextPeriod>
							</LogoText>
						</LogoContainer>
					</Link>

					<MenuHeading style={{ marginBottom: 25 }}>Menu</MenuHeading>
					<MenuItemContainer>
						{menuItems.map((menuItem, index) => (
							<>
								<FlexRow key={index}>
									<menuItem.icon
										style={{ color: menuItem.selected ? '#D22F27' : '#6B6C74' }}
										size={30}
									/>
									<MenuText
										style={{ color: menuItem.selected ? '#fff' : '#6B6C74' }}
									>
										{menuItem.text}
									</MenuText>
								</FlexRow>
							</>
						))}
					</MenuItemContainer>
				</NavBar>
				{props.children}
			</Container>
		</Wrapper>
	);
};

export default Layout;
